# finnish
on load:
    set {lang::FI::saved_variable_data} to "&7Päivitettiin &fVariable Daata."
    set {lang::FI::balance} to "&aRahaa"
    set {lang::FI::cooldownMessage} to "&cOdota Hetkesi."
    set {lang::FI::languages} to "&dKielejä"
    set {lang::FI::settings} to "&lASETUKSET"
    set {lang::FI::return} to "Takaisin"
    set {lang::FI::upgradables} to "Päivitettävät"
    set {lang::FI::itemDrop} to "Esineiden pudottaminen on poistettu käytöstä. Jos jokin on vialla, ota yhteyttä henkilökuntaan."
    set {lang::FI::upgradeTools} to "Päivitä työkalut"
    set {lang::FI::buyHoes} to "Päivitä kerääjä"
    set {lang::FI::harvesterShop} to "Kerääjän kauppa"
    set {lang::FI::requirements} to "&8-- &Vaatimukset &8--"