# russian
on load:
    set {lang::RU::saved_variable_data} to "&7Данные переменных &fобновлены."
    set {lang::RU::balance} to "&aбаланс"
    set {lang::RU::cooldownMessage} to "&cПожалуйста, не спамьте команды."
    set {lang::RU::languages} to "&dЯзыки"
    set {lang::RU::settings} to "&lНАСТРОЙКИ"
    set {lang::RU::return} to "Назад"
    set {lang::RU::upgradables} to "Улучшения"
    set {lang::RU::itemDrop} to "Выбрасывание предметов отключено. Если что-то не так, свяжитесь с персоналом"
    set {lang::RU::upgradeTools} to "Улучшить инструменты"
    set {lang::RU::buyHoes} to "Улучшить жатку"
    set {lang::RU::harvesterShop} to "Магазин жаток"
    set {lang::RU::requirements} to "&8-- &7Требования &8--"