command giveHoe <player> <integer>:
    permission: op
    trigger:
        give {hoes::%arg-2%} to arg-1

on load:
    set {hoes::1} to unbreakable wooden hoe named "<#5c5730>Broken Harvester" with lore "&8Starter ☆☆☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::1::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::1::mult}%"
    wait 1 tick
    set {hoes::1::blast} to 0
    set {hoes::1::mult} to 1.05



    set {hoes::2} to unbreakable wooden hoe named "<#5e502d>Rotten Harvester" with lore "&8Common ★☆☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::2::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::2::mult}%"
    wait 1 tick
    set {hoes::2::blast} to 0
    set {hoes::2::mult} to 1.08
    
    set {hoes::2::price} to 1350
    set {hoes::2::tokens} to 1
    set {hoes::2::level} to 4



    set {hoes::3} to unbreakable wooden hoe named "<#cf7f29>Rusted Harvester" with lore "&8Common ★☆☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::3::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::3::mult}%"
    wait 1 tick
    set {hoes::3::blast} to 0
    set {hoes::3::mult} to 1.1

    set {hoes::3::price} to 1400
    set {hoes::3::tokens} to 3
    set {hoes::3::level} to 5



    set {hoes::4} to unbreakable wooden hoe named "<#a4632d>Decayed Wooden Harvester" with lore "&8Common ★☆☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::4::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::4::mult}%"
    wait 1 tick
    set {hoes::4::blast} to 0
    set {hoes::4::mult} to 1.11

    set {hoes::4::price} to 1800
    set {hoes::4::tokens} to 5
    set {hoes::4::level} to 10



    set {hoes::5} to unbreakable wooden hoe named "<#A4722D>Wooden Harvester" with lore "&8Common ★☆☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::5::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::5::mult}%"
    wait 1 tick
    set {hoes::5::blast} to 0
    set {hoes::5::mult} to 1.13

    set {hoes::5::price} to 2500
    set {hoes::5::tokens} to 5
    set {hoes::5::level} to 18



    set {hoes::6} to unbreakable wooden hoe named "<#9c7135>Hard Wood Harvester" with lore "&8Common ★☆☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::6::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::6::mult}%"
    wait 1 tick
    set {hoes::6::blast} to 0
    set {hoes::6::mult} to 1.15

    set {hoes::6::price} to 3100
    set {hoes::6::tokens} to 6
    set {hoes::6::level} to 23



    set {hoes::7} to unbreakable wooden hoe named "<#ffe030>Sun Dried Harvester" with lore "&8Common ★☆☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::7::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::7::mult}%"
    wait 1 tick
    set {hoes::7::blast} to 0
    set {hoes::7::mult} to 1.18

    set {hoes::7::price} to 3750
    set {hoes::7::tokens} to 6
    set {hoes::7::level} to 26


    # dont forget to change the value on the lore
    set {hoes::8} to unbreakable wooden hoe named "<#b59567>Artificial Wooden Harvester" with lore "&8Uncommon ★★☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::8::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::8::mult}%"
    wait 1 tick
    set {hoes::8::blast} to 0
    set {hoes::8::mult} to 1.2

    set {hoes::8::price} to 4075
    set {hoes::8::tokens} to 6
    set {hoes::8::level} to 30

    # dont forget to change the value on the lore
    set {hoes::9} to unbreakable wooden hoe named "<#d69554>Pressed Wood Harvester" with lore "&8Uncommon ★★☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::9::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::9::mult}%"
    wait 1 tick
    set {hoes::9::blast} to 0
    set {hoes::9::mult} to 1.25

    set {hoes::9::price} to 4200
    set {hoes::9::tokens} to 6
    set {hoes::9::level} to 34

    # dont forget to change the value on the lore
    set {hoes::10} to unbreakable stone hoe named "<#a8a8a8>Slate Stone Harvester" with lore "&8Uncommon ★★☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::10::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::10::mult}%"
    wait 1 tick
    set {hoes::10::blast} to 0
    set {hoes::10::mult} to 1.45

    set {hoes::10::price} to 4900
    set {hoes::10::tokens} to 7
    set {hoes::10::level} to 38

    # dont forget to change the value on the lore
    set {hoes::11} to unbreakable stone hoe named "<#a8a8a8>Limestone Harvester" with lore "&8Uncommon ★★☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::11::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::11::mult}%"
    wait 1 tick
    set {hoes::11::blast} to 0
    set {hoes::11::mult} to 1.60

    set {hoes::11::price} to 6000
    set {hoes::11::tokens} to 8
    set {hoes::11::level} to 42

    # dont forget to change the value on the lore
    set {hoes::12} to unbreakable stone hoe named "<#a8a8a8>Stone Harvester" with lore "&8Uncommon ★★☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::12::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::12::mult}%"
    wait 1 tick
    set {hoes::12::blast} to 0
    set {hoes::12::mult} to 1.81

    set {hoes::12::price} to 8000
    set {hoes::12::tokens} to 8
    set {hoes::12::level} to 46

    # dont forget to change the value on the lore
    set {hoes::13} to unbreakable stone hoe named "<#a8a8a8>Granite Harvester" with lore "&8Uncommon ★★☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::13::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::13::mult}%"
    wait 1 tick
    set {hoes::13::blast} to 0
    set {hoes::13::mult} to 3.99

    set {hoes::13::price} to 11000
    set {hoes::13::tokens} to 9
    set {hoes::13::level} to 49

    # dont forget to change the value on the lore
    set {hoes::14} to unbreakable stone hoe named "<#6e6c6b>Flint Harvester" with lore "&8Uncommon ★★☆☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::14::blast} + 1% block" and " &8&l| <#45CF30>Mult: &fx%{hoes::14::mult}%"
    wait 1 tick
    set {hoes::14::blast} to 0
    set {hoes::14::mult} to 5.05

    set {hoes::14::price} to 16000
    set {hoes::14::tokens} to 11
    set {hoes::14::level} to 54

    # dont forget to change the value on the lore
    set {hoes::15} to unbreakable iron hoe named "<#e8d18e>Sandstone Harvester" with lore "<#3881c9>Rare ★★★☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::15::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::15::mult}%"
    wait 1 tick
    set {hoes::15::blast} to 1
    set {hoes::15::mult} to 7.95

    set {hoes::15::price} to 19700
    set {hoes::15::tokens} to 13
    set {hoes::15::level} to 65

    # dont forget to change the value on the lore
    set {hoes::16} to unbreakable iron hoe named "<#fcf3d7>Glass Harvester" with lore "<#3881c9>Rare ★★★☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::16::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::16::mult}%"
    wait 1 tick
    set {hoes::16::blast} to 1
    set {hoes::16::mult} to 9.5

    set {hoes::16::price} to 23500
    set {hoes::16::tokens} to 14
    set {hoes::16::level} to 78

    # dont forget to change the value on the lore
    set {hoes::17} to unbreakable iron hoe named "<#f5f2eb>Iron Harvester" with lore "<#3881c9>Rare ★★★☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::17::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::17::mult}%"
    wait 1 tick
    set {hoes::17::blast} to 1
    set {hoes::17::mult} to 12.75

    set {hoes::17::price} to 38900
    set {hoes::17::tokens} to 17
    set {hoes::17::level} to 83

    # dont forget to change the value on the lore
    set {hoes::18} to unbreakable iron hoe named "<#abaaa9>Steel Harvester" with lore "<#3881c9>Rare ★★★☆☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::18::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::18::mult}%"
    wait 1 tick
    set {hoes::18::blast} to 1
    set {hoes::18::mult} to 15.50

    set {hoes::18::price} to 52500
    set {hoes::18::tokens} to 20
    set {hoes::18::level} to 92

    # dont forget to change the value on the lore
    set {hoes::19} to unbreakable iron hoe named "<#807f7e>Tungsten Harvester" with lore "<#8142ff>Epic ★★★★☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::19::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::19::mult}%"
    wait 1 tick
    set {hoes::19::blast} to 1
    set {hoes::19::mult} to 18.25

    set {hoes::19::price} to 80000
    set {hoes::19::tokens} to 24
    set {hoes::19::level} to 98

    # dont forget to change the value on the lore
    set {hoes::20} to unbreakable golden hoe named "<#f58989>Cursed Harvester" with lore "<#8142ff>Epic ★★★★☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::20::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::20::mult}%"
    wait 1 tick
    set {hoes::20::blast} to 1
    set {hoes::20::mult} to 22.44

    set {hoes::20::price} to 100000
    set {hoes::20::tokens} to 28
    set {hoes::20::level} to 107

    # dont forget to change the value on the lore
    set {hoes::21} to unbreakable golden hoe named "<#cf8327>Molten Harvester" with lore "<#8142ff>Epic ★★★★☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::21::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::21::mult}%"
    wait 1 tick
    set {hoes::21::blast} to 1
    set {hoes::21::mult} to 28.89

    set {hoes::21::price} to 123456
    set {hoes::21::tokens} to 30
    set {hoes::21::level} to 112

    # dont forget to change the value on the lore
    set {hoes::22} to unbreakable diamond hoe named "<#51e1e8>Water Harvester" with lore "<#8142ff>Epic ★★★★☆☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::22::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::22::mult}%"
    wait 1 tick
    set {hoes::22::blast} to 1
    set {hoes::22::mult} to 48.17

    set {hoes::22::price} to 175540
    set {hoes::22::tokens} to 43
    set {hoes::22::level} to 153

    # dont forget to change the value on the lore
    set {hoes::23} to unbreakable diamond hoe with glint named "<#00ffd6>H<#06ebd5>y<#0bd7d4>p<#11c3d3>e<#17afd2>r<#1c9bd1>n<#2287d0>o<#2773cf>v<#2d5fce>a Harvester" with lore "<#b0db23>Legendary ★★★★★☆☆" and " " and " &8• <#F48566>Blast: &f%{hoes::23::blast} + 1% blocks" and " &8&l| <#45CF30>Mult: &fx%{hoes::23::mult}%"
    wait 1 tick
    set {hoes::23::blast} to 2
    set {hoes::23::mult} to 64.17

    set {hoes::23::price} to 212440
    set {hoes::23::tokens} to 54
    set {hoes::23::level} to 170