function openUpgradeToolsMenu(p: player):
    set {_s} to chest inventory with 3 rows named "%{lang::%{-language::%uuid of {_p}%}%::upgradeTools}%"
    set slot 13 of {_s} to diamond hoe named "%{lang::%{-language::%uuid of {_p}%}%::buyHoes}%"
    open {_s} to {_p}

function openHarvesterShop(p: player):
    set {_s} to chest inventory with 5 rows named "%{lang::%{-language::%uuid of {_p}%}%::harvesterShop}%"
    set slot 22 of {_s} to {hoes::%{-hoe::%uuid of {_p}%} + 1%} with lore {lang::%{-language::%uuid of {_p}%}%::requirements} and "<#8aed4c>%{lang::%{-language::%uuid of {_p}%}%::price}%:   $%{hoes::%{-hoe::%uuid of {_p}%} + 1%::price}%" and "<#edaa4c>%{lang::%{-language::%uuid of {_p}%}%::tokens}%: %{hoes::%{-hoe::%uuid of {_p}%} + 1%::tokens}%" and "<#edda4c>%{lang::%{-language::%uuid of {_p}%}%::level}%:   %{hoes::%{-hoe::%uuid of {_p}%} + 1%::level}%" and {lang::%{-language::%uuid of {_p}%}%::comparison} and "<#F48566>%{lang::%{-language::%uuid of {_p}%}%::blast}%: &f%{hoes::%{-hoe::%uuid of {_p}%}%::blast}% <#8aed4c>+ %{hoes::%{-hoe::%uuid of {_p}%} + 1%::blast} - {hoes::%{-hoe::%uuid of {_p}%}%::blast}% &f%{lang::%{-language::%uuid of {_p}%}%::blocks}%" and "<#45CF30>%{lang::%{-language::%uuid of {_p}%}%::mult}%: &fx%{hoes::%{-hoe::%uuid of {_p}%}%::mult}% <#8aed4c>+ %{hoes::%{-hoe::%uuid of {_p}%} + 1%::mult} - {hoes::%{-hoe::%uuid of {_p}%}%::mult}%"
    set slot 23 of {_s} to nether star named "<#4cd8ed>View All Harvesters!" with lore "&8Usage Utility" and " " and {lang::%{-language::%uuid of {_p}%}%::rightclickopen}
    open {_s} to {_p}