# common, uncommon, rare, epic, legendary, master, grandmaster
command loadAbilities:
    permission: op
    trigger:
        loadAbilities()

on load:
    loadAbilities()

function loadAbilities():

    set {ability::1} to feather named "<#d1d1d1>Dash" with lore "&8%{ability::1::rarity}%" and "" and "<#b5b59a>Cooldown: %{ability::1::cooldown}%" and "" and "&8-- <#b5b59a>Usage &8--" and "<#f0eec5>Look at your desired direction and" and "<#f0eec5>Shift + Right Click with your harvester."
    set {ability::1::cooldown} to 2 seconds
    set {ability::1::rarity} to "Starter"

    set {ability::2} to wind charge named "<#85c9c7>Shockwave" with lore "&8%{ability::2::rarity}%" and "" and "<#b5b59a>Cooldown: %{ability::2::cooldown}%" and "" and "&8-- <#b5b59a>Usage &8--" and "<#f0eec5>Shift + Right Click with your harvester."
    set {ability::2::cooldown} to 5 seconds 
    set {ability::2::rarity} to "Common"

    set {ability::3} to echo shard with glint named "<#734bc9>Lightning Storm" with lore "&8%{ability::3::rarity}%" and "" and "<#b5b59a>Cooldown: %{ability::3::cooldown}%" and "" and "&8-- <#b5b59a>Usage &8--" and "<#f0eec5>Look at the target object and" and "<#f0eec5>Shift + Right Click with your harvester."
    set {ability::3::cooldown} to 45 seconds
    set {ability::3::rarity} to "<#3881c9>Rare"

    set {ability::4} to amethyst shard with glint named "<#c938a3>Orbital Strike" with lore "&8%{ability::4::rarity}%" and "" and "<#b5b59a>Cooldown: %{ability::4::cooldown}%" and "" and "&8-- <#b5b59a>Usage &8--" and "<#f0eec5>Look at the target object and" and "<#f0eec5>Shift + Right Click with your harvester."
    set {ability::4::cooldown} to 1 minute
    set {ability::4::rarity} to "<#aa38c9>Master"

    set {ability::5} to fire charge with glint named "<#ed9e4e>Meteor Shower" with lore "&8%{ability::5::rarity}%" and "" and "<#b5b59a>Cooldown: %{ability::5::cooldown}%" and "" and "&8-- <#b5b59a>Usage &8--" and "<#f0eec5>Shift + Right Click with your harvester."
    set {ability::5::cooldown} to 1 minute
    set {ability::5::rarity} to "<#FF4D4D>Grandmaster"

    # possibly 100 more