function getTargetObject(p: player, dist: int = 25) :: location:
    set {_targetBlock} to target block of {_p}
    set {_targetEntity} to target entity of {_p}
    
    if {_targetEntity} is set:
        distance between location of {_p} and location of {_targetEntity} <= {_dist}
        set {_x} to x of location of {_targetEntity}
        set {_z} to z of location of {_targetEntity}
    else:
        if {_targetBlock} is set:
            if distance between location of {_p} and location of {_targetBlock} <= {_dist}:
                set {_x} to x of location of {_targetBlock}
                set {_z} to z of location of {_targetBlock}
            else:
                set {_yaw} to yaw of {_p}
                set {_x} to x of {_p} + (sin({_yaw}) * -1) * {_dist}
                set {_z} to z of {_p} + cos({_yaw}) * {_dist}
        else:
            set {_yaw} to yaw of {_p}
            set {_x} to x of {_p} + (sin({_yaw}) * -1) * {_dist}
            set {_z} to z of {_p} + cos({_yaw}) * {_dist}

    set {_strikeY} to y of highest block at location({_x}, 64, {_z}, world of {_p})

    breakWheat({_p}, location({_x}, {_strikeY} + 1, {_z}))
    return location({_x}, {_strikeY} + 1, {_z})