function runAbility(p: player):
    if {ability::%{-abilities::%uuid of {_p}%}%::name} is "dash":
        abilityDash({_p})

    else if {ability::%{-abilities::%uuid of {_p}%}%::name} is "shockwave":
        abilityShockwave({_p})

    else if {ability::%{-abilities::%uuid of {_p}%}%::name} is "rain":
        abilityRain({_p}, 15 seconds, {-abilitySkill::%uuid of {_p}%} + 4)

    else if {ability::%{-abilities::%uuid of {_p}%}%::name} is "lightning":
        abilityLightningStorm({_p})

    else if {ability::%{-abilities::%uuid of {_p}%}%::name} is "orbital":
        abilityOrbitalStrike({_p}, 20 seconds)

    else if {ability::%{-abilities::%uuid of {_p}%}%::name} is "meteor":
        abilityMeteorShower({_p})