function spinAbility(p: player):
    set {_a} to random integer between 1 and 100

    broadcast {_a}

    if {_a} is less than 30:
        setAbility({_p}, 1)

    else if {_a} is between 30 and 50:
        setAbility({_p}, 2)
    
    else if {_a} is between 50 and 75:
        setAbility({_p}, 3)

    else if {_a} is between 75 and 85:
        setAbility({_p}, 5)

    else if {_a} is between 85 and 95:
        setAbility({_p}, 5)

    else if {_a} is between 95 and 100:
        setAbility({_p}, 6)
        broadcast "%{_p}% has got meteor shower"