function openSettingsLanguages(p: player):
    set {_s} to chest inventory with 3 rows named "%{lang::%{-language::%uuid of {_p}%}%::settings}% - %{lang::%{-language::%uuid of {_p}%}%::languages}%"

    set slot 0 of {_s} to (writable book) named "English (EN)" with lore ("&a&lSELECTED" if {-language::%uuid of {_p}%} is "EN" else " ")
    set slot 1 of {_s} to (writable book) named "German (DE)" with lore ("&a&lSELECTED" if {-language::%uuid of {_p}%} is "DE" else " ")
    set slot 2 of {_s} to (writable book) named "Finnish (FI)" with lore ("&a&lSELECTED" if {-language::%uuid of {_p}%} is "FI" else " ")
    set slot 3 of {_s} to (writable book) named "Russian (RU)" with lore ("&a&lSELECTED" if {-language::%uuid of {_p}%} is "RU" else " ")
    set slot 4 of {_s} to (writable book) named "Spanish (SPA)" with lore ("&a&lSELECTED" if {-language::%uuid of {_p}%} is "SPA" else " ")

    set slot 26 of {_s} to barrier named "&c%{lang::%{-language::%uuid of {_p}%}%::return}%"
    open {_s} to {_p}

function settingsLanguageSelection(i: integer, p: player):
    
    if {_i} is 0:
        setLanguage({_p}, "EN")
    else if {_i} is 1:
        setLanguage({_p}, "DE")
    else if {_i} is 2:
        setLanguage({_p}, "FI")
    else if {_i} is 3:
        setLanguage({_p}, "RU")
    else if {_i} is 4:
        setLanguage({_p}, "SPA")

    openSettingsLanguages({_p})

    if {_i} is 26:
        openSettings({_p})