on inventory click:
    cancel event
    if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::settings}%":
        if event-slot is 15:
            openSettingsLanguages(player)

    if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::settings}% - %{lang::%{-language::%uuid of player%}%::languages}%":
        settingsLanguageSelection(index of event-slot, player)

    if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::upgradeTools}%":
        if event-slot is 14:
            openHarvesterShop(player)

    if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::harvesterShop}%":
        if event-slot is 12:
            confirmPurchase(player)
        
        if event-slot is 14:
            showAllHarvesters(player)

    if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::allHarvesters}%":
        if event-slot is 40:
            openHarvesterShop(player)