on inventory click:
    cancel event
    if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::settings}%":
        if event-slot is 15:
            openSettingsLanguages(player)

    else if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::settings}% - %{lang::%{-language::%uuid of player%}%::languages}%":
        settingsLanguageSelection(index of event-slot, player)

    else if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::upgradeTools}%":
        if event-slot is 14:
            openHarvesterShop(player)
        else if event-slot is 12:
            openAbilityShop(player)

    else if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::harvesterShop}%":
        if event-slot is 12:
            confirmPurchase(player)
        
        else if event-slot is 14:
            showAllHarvesters(player)

    else if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::allHarvesters}%":
        if event-slot is 40:
            openHarvesterShop(player)

    else if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::abilityShop}%":
        if event-slot is 12:
            confirmAbilityPurchase(player)

        else if event-slot is 14:
            showAllAbilities(player)

    else if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::allAbilities}%":
        if event-slot is 40:
            openAbilityShop(player)

    else if name of event-inventory is "%{lang::%{-language::%uuid of player%}%::skillsUpgrade}%":
        if event-slot is 16:
            upgradeSkillAbility(player)

        openSkillsUpgrade(player)