function openSkillsUpgrade(p: player):
    set {_s} to chest inventory with 3 rows named "%{lang::%{-language::%uuid of {_p}%}%::skillsUpgrade}%"

    set slot 10 of {_s} to shears named "<#F48566>Blast &8• &f%{-data::%uuid of {_p}%::blast}% %{lang::%{-language::%uuid of {_p}%}%::blocks}%" with lore "&8%{lang::%{-language::%uuid of {_p}%}%::noConfirmation}%" and "" and " &8• &7%{lang::%{-language::%uuid of {_p}%}%::increaseWheatBreaking}%" and " &8&l| &7%{lang::%{-language::%uuid of {_p}%}%::radiusforharvesters}%" and "" and "&7%{lang::%{-language::%uuid of {_p}%}%::upgradeFor}% <#edda4c>%((({-data::%uuid of {_p}%::blast} + 1) * 20))% %{lang::%{-language::%uuid of {_p}%}%::tokens}% &8(<#edda4c>%{-token::%uuid of {_p}%}%&8)"

    set slot 12 of {_s} to experience bottle named "<#9ee03a>XP Multiplier &8• &f%{xpmult::%uuid of {_p}%}%" with lore "&8%{lang::%{-language::%uuid of {_p}%}%::noConfirmation}%" and "" and " &8• &7%{lang::%{-language::%uuid of {_p}%}%::gainxpfaster}%" and " &8&l| &7%{lang::%{-language::%uuid of {_p}%}%::tolevelupfaster}%" and "" and "&7%{lang::%{-language::%uuid of {_p}%}%::upgradeFor}% <#edda4c>2 %{lang::%{-language::%uuid of {_p}%}%::tokens}% &8(<#edda4c>%{-token::%uuid of {_p}%}%&8)"

    set slot 14 of {_s} to leather boots named "<#3ac2e0>Speed &8• &f%{-speed::%uuid of {_p}%}%" with lore "&8%{lang::%{-language::%uuid of {_p}%}%::noConfirmation}%" and "" and " &8• &7%{lang::%{-language::%uuid of {_p}%}%::fasterwhile}%" and " &8&l| &7%{lang::%{-language::%uuid of {_p}%}%::holdingharvester}%" and "" and "&7%{lang::%{-language::%uuid of {_p}%}%::upgradeFor}% <#edda4c>2 %{lang::%{-language::%uuid of {_p}%}%::tokens}% &8(<#edda4c>%{-token::%uuid of {_p}%}%&8)"
    
    set slot 16 of {_s} to nether star named "<#e03a88>Ability Skill &8• &f%{-abilitySkill::%uuid of {_p}%} - 1%" with lore "&8%{lang::%{-language::%uuid of {_p}%}%::noConfirmation}%" and " " and " &8• &7%{lang::%{-language::%uuid of {_p}%}%::abilitymorepowerful}%" and " &8&l| &c%{lang::%{-language::%uuid of {_p}%}%::doesnot}% &7%{lang::%{-language::%uuid of {_p}%}%::reducecooldown}%" and "" and ("&7%{lang::%{-language::%uuid of {_p}%}%::upgradeFor}% <#edda4c>%(({-abilitySkill::%uuid of {_p}%} * 5) + 5)% %{lang::%{-language::%uuid of {_p}%}%::tokens}% &8(<#edda4c>%{-token::%uuid of {_p}%}%&8)" if {-abilitySkill::%uuid of {_p}%} is less than 9 else "&cMAX")
    
    open {_s} to {_p}

function upgradeSkillAbility(p: player):

    if {-abilitySkill::%uuid of {_p}%} is less than or equal to 8:
        if {-token::%uuid of {_p}%} is higher or equal to (({-abilitySkill::%uuid of {_p}%} * 5) + 5):
            addToken({_p}, (({-abilitySkill::%uuid of {_p}%} * 5) + 5) * -1)
            addAbilitySkill({_p}, 1)
        else:
            send "&c%{lang::%{-language::%uuid of {_p}%}%::insufficientTokens}%" to {_p}
    else:
        send "&c%{lang::%{-language::%uuid of {_p}%}%::maxSkillLevel}%" to {_p}

function upgradeSkillXP(p: player):

    if {-token::%uuid of {_p}%} is higher or equal to 2:
        addToken({_p}, -2)
        addXPMult({_p}, 0.05)
    else:
        send "&c%{lang::%{-language::%uuid of {_p}%}%::insufficientTokens}%" to {_p}

function upgradeSkillBlast(p: player):

    if {-data::%uuid of {_p}%::blast} is less than 6:
        if {-token::%uuid of {_p}%} is higher or equal to (({-data::%uuid of {_p}%::blast} + 1) * 20):
            addToken({_p}, ((({-data::%uuid of {_p}%::blast} + 1) * 20) * -1))
            addBlast({_p}, 1)
        else:
            send "&c%{lang::%{-language::%uuid of {_p}%}%::insufficientTokens}%" to {_p}
    else:
        send "&c%{lang::%{-language::%uuid of {_p}%}%::maxSkillLevel}%" to {_p}

function upgradeSkillSpeed(p: player):

    if {-token::%uuid of {_p}%} is higher or equal to 2:
        addToken({_p}, -2)
        addSpeed({_p}, 0.02)
    else:
        send "&c%{lang::%{-language::%uuid of {_p}%}%::insufficientTokens}%" to {_p}