on load:
    set {-wheatQueue::*} to location(0, 0, 0)

function loadWheat():
    loop {-wheatQueue::*}:
        set block at loop-value to wheat[age=7]
        clear {-wheatQueue::%loop-index%}

function breakWheat(p: player, loc: location):
    if {timeSinceLastBreak::%uuid of {_p}%} is less than 3 seconds ago:
        set {-wl::%uuid of {_p}%} to 0

    set {timeSinceLastBreak::%uuid of {_p}%} to now
    
    set {_oo} to 0

    if {-data::%uuid of {_p}%::blast} is 0:
        set block at {_loc} to air
        set {_oo} to 1
        add {_loc} to {-wheatQueue::*}
        add 1 to {-wl::%uuid of {_p}%}
    
    else:
        loop blocks in radius ({-data::%uuid of {_p}%::blast} + {hoes::%{-hoe::%uuid of {_p}%}%::blast}) of {_loc}:
            loop-block is wheat

            set block at (location of loop-block) to air
            add location of loop-block to {-wheatQueue::*}
            add 1 to {-wl::%uuid of {_p}%}
            add 1 to {_oo}

    send action bar "&a+$%calculateBalance({_p}, {-wl::%uuid of {_p}%})% &8(&e$%calculateBalance({_p}, {_oo})%&8)" to {_p}
    addBalance({_p}, calculateBalance({_p}, {_oo}))