every 3 minutes:
    if {c} is not set:
        set {c} to 1
    add 1 to {c}
    if {c} is higher than 6:
        set {c} to 1
    broadcast {broadcast::%{c}%::*}

command broadcast <integer>:
    permission: op 
    trigger:
        broadcast {broadcast::%arg-1%::*}

on load:
    set {broadcast::1::1} to " "
    set {broadcast::1::2} to "&a&lSupport Us!"
    set {broadcast::1::3} to " &8• <#b5b59a>We need to pay for rent and server host too"
    set {broadcast::1::4} to " &8&l| <#b5b59a>we would appreciate a lot if you donated to us <3"
    set {broadcast::1::5} to "&aBreakWheat.tebex.io <#b5b59a>or &a/buy &7| &a/donate"
    set {broadcast::1::6} to " "

    set {broadcast::2::1} to " "
    set {broadcast::2::2} to "&9&lJoin our community! &c(13+ ONLY)"
    set {broadcast::2::3} to " &8• <#b5b59a>Since you are playing our server, you are one of us now."
    set {broadcast::2::4} to " &8&l| <#b5b59a>join our community to not miss updates, also make friends for first time"
    set {broadcast::2::5} to "&9discord.gg/atcHyUJR7b <#b5b59a>or &9/discord"
    set {broadcast::2::6} to " "

    set {broadcast::3::1} to " "
    set {broadcast::3::2} to "&e&lBugs and Issues"
    set {broadcast::3::3} to " &8• <#b5b59a>If you're a developer, or any normal player and found a bug or an issue with the server"
    set {broadcast::3::4} to " &8&l| <#b5b59a>please report it to the developer of the server to get it fixed <3"
    set {broadcast::3::5} to "&ediscord.gg/atcHyUJR7b <#b5b59a>or &e/discord"
    set {broadcast::3::6} to " "

    set {broadcast::4::1} to " "
    set {broadcast::4::2} to "&b&lInvite your friends!"
    set {broadcast::4::3} to " &8• <#b5b59a>If you enjoy this server, we'd appreciate if you spread the word."
    set {broadcast::4::4} to " &8&l| <#b5b59a>You guys are what made this server possible!"
    set {broadcast::4::5} to "&bdiscord.gg/atcHyUJR7b <#b5b59a>or &b/discord"
    set {broadcast::4::6} to " "

    set {broadcast::5::1} to " "
    set {broadcast::5::2} to "&6&lTIP"
    set {broadcast::5::3} to " &8• <#b5b59a>Gaining levels is the fastest way to get tokens"
    set {broadcast::5::4} to " &8&l| <#b5b59a>if you are a new player!"
    set {broadcast::5::5} to " "