# load yml "plugins/Skript/scripts/yaml/data.yml"
# set yml value "users.uuid001.balance" from "data" to 5000
# yml value "users.uuid001.balance" from "data" // get value
# save yml "data"
# unload yml "data"

placeholderapi placeholder with the prefix "skript":
    if the identifier is "balance":
        set the result to shortNum({-data::%uuid of player%::balance})
    else if the identifier is "tokens":
        set the result to {-token::%uuid of player%}
    else if the identifier is "levelprogress":
        set the result to ({points::%uuid of player%} / {pointsReq::%uuid of player%}) * 100
    else if the identifier is "points":
        set the result to "<#e3d956>%{points::%uuid of player%}% &8/ <#98de5b>%{pointsReq::%uuid of player%}%"
    else if the identifier is "level":
        set the result to {-level::%uuid of player%}

on load:
    load yml "plugins/Skript/scripts/yaml/data.yml" as "data"

on join:
    saveVariableData(player)

on quit:
    saveVariableData(player)

#   ---------------------------------------------------
#   ---------------------------------------------------
command reloadyml:
    permission: op
    trigger:
        reload(player)

        loop all players:
            saveVariableData(loop-player)
            wait 1 tick
#   ---------------------------------------------------
#   ---------------------------------------------------

command resetLevel <player>:
    permission: op
    trigger:
        set {points::%uuid of arg-1%} to 1
        set {pointsReq::%uuid of arg-1%} to 250
        setLevel(arg-1, 1)

function saveVariableData(p: player, b: boolean = true):

    {_p} is a player

    set yml value "users.%uuid of {_p}%.balance" from "data" to {-data::%uuid of {_p}%::balance}
    set yml value "users.%uuid of {_p}%.tokens" from "data" to {-token::%uuid of {_p}%}

    set {-data::%uuid of {_p}%::blast} to fetchBlast({_p})
    set {-data::%uuid of {_p}%::balance} to fetchBalance({_p})
    set {-language::%uuid of {_p}%} to fetchLanguage({_p})
    set {-multiplier::%uuid of {_p}%} to fetchMultiplier({_p})
    set {-token::%uuid of {_p}%} to fetchTokens({_p})
    set {-speed::%uuid of {_p}%} to fetchSpeed({_p})
    set {-hoe::%uuid of {_p}%} to fetchHoe({_p})
    set {-level::%uuid of {_p}%} to fetchLevel({_p})
    set {-tokenChance::%uuid of {_p}%} to fetchTokenChance({_p})
    set {-abilitySkill::%uuid of {_p}%} to fetchAbilitySkill({_p})
    set {-abilities::%uuid of {_p}%} to fetchAbility({_p})

    if {points::%uuid of {_p}%} is not set:
        set {points::%uuid of {_p}%} to 1
    if {pointsReq::%uuid of {_p}%} is not set:
        set {pointsReq::%uuid of {_p}%} to 250

    {_b} is true
    send action bar "%{lang::%{-language::%uuid of {_p}%}%::saved_variable_data}%" to {_p}

local function save():
    if yml "data" isn't loaded:
        load yml "plugins/Skript/scripts/yaml/data.yml" as "data"
    save yml "data"

#   !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !!!
#   !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !!!
#   FOR FUTURE ME: RELOAD **DOES** NOT SAVE, IT LOADS FROM CURRENT YAML FILE : IT DOES NOT SAVE NEW INFORMATION
#   SO DATA CAN BE LOST, ONLY USE THIS WHEN TESTING OR SAVE FIRST THEN RELOAD 
#   !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !! --- !!!
#   !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !! !!!! !!!
local function reload(p: player):
    unload yml "data"
    load yml "plugins/Skript/scripts/yaml/data.yml" as "data"
    send "reloaded yml" to {_p}



local function init(p: player):
    if yml "data" isn't loaded:
        load yml "plugins/Skript/scripts/yaml/data.yml" as "data"
    set {_uuid} to (uuid of {_p})

    if yml path "users.%{_uuid}%.balance" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.balance" from "data" to 0

    if yml path "users.%{_uuid}%.tokens" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.tokens" from "data" to 0

    if yml path "users.%{_uuid}%.blast" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.blast" from "data" to 0

    if yml path "users.%{_uuid}%.multiplier" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.multiplier" from "data" to 1

    if yml path "users.%{_uuid}%.speed" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.speed" from "data" to 0

    if yml path "users.%{_uuid}%.lang" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.lang" from "data" to "EN"

    if yml path "users.%{_uuid}%.hoe" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.hoe" from "data" to 1

    if yml path "users.%{_uuid}%.level" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.level" from "data" to 1

    if yml path "users.%{_uuid}%.tokenChance" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.tokenChance" from "data" to 0.001

    if yml path "users.%{_uuid}%.abilitySkill" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.abilitySkill" from "data" to 1

    if yml path "users.%{_uuid}%.ability" in "data" doesn't exist:
        set yml value "users.%{_uuid}%.ability" from "data" to 1

    save()

#   ====================================#   ====================================
#   FFFFF EEE TT CC HHH I NN GGG #   ====================================
#   FF   EEE TT CC HHH I NN GGG  #   ====================================
#   ====================================#   ====================================

function fetchLanguage(p: player) :: text:
    init({_p})
    return (yml value "users.%uuid of {_p}%.lang" from "data")

function fetchBalance(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.balance" from "data")

function fetchBlast(p: player) :: integer:
    init({_p})
    return (yml value "users.%uuid of {_p}%.blast" from "data")

function fetchMultiplier(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.multiplier" from "data")

function fetchSpeed(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.speed" from "data")

function fetchHoe(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.hoe" from "data")

function fetchLevel(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.level" from "data")

function fetchTokens(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.tokens" from "data")

function fetchTokenChance(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.tokenChance" from "data")

function fetchAbilitySkill(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.abilitySkill" from "data")

function fetchAbility(p: player) :: number:
    init({_p})
    return (yml value "users.%uuid of {_p}%.ability" from "data")

#
# ADD // REMOVE
# ADD // REMOVE
#
function addBalance(p: player, amount: number):
    add {_amount} to {-data::%uuid of {_p}%::balance}

function addToken(p: player, amount: number):
    add {_amount} to {-token::%uuid of {_p}%}

function addLevel(p: player, amount: number):
    set yml value "users.%uuid of {_p}%.level" from "data" to (fetchLevel({_p}) + {_amount})
    saveVariableData({_p}, false)

function addAbilitySkill(p: player, amount: number):
    set yml value "users.%uuid of {_p}%.abilitySkill" from "data" to (fetchAbilitySkill({_p}) + {_amount})
    saveVariableData({_p}, false)

#
# SET
# SET
#
function setLevel(p: player, i: int):
    init({_p})
    set yml value "users.%uuid of {_p}%.level" from "data" to {_i}
    saveVariableData({_p}, false)

function setLanguage(p: player, lang: text):
    init({_p})
    set yml value "users.%uuid of {_p}%.lang" from "data" to {_lang}
    play sound "entity.experience_orb.pickup" with volume 1 and pitch 1 to {_p}
    saveVariableData({_p}, false)

function setHoe(p: player, i: integer):
    init({_p})
    set yml value "users.%uuid of {_p}%.hoe" from "data" to {_i}
    play sound "entity.experience_orb.pickup" with volume 1 and pitch 1 to {_p}
    saveVariableData({_p}, false)

function setAbility(p: player, i: integer):
    init({_p})
    set yml value "users.%uuid of {_p}%.ability" from "data" to {_i}
    play sound "entity.experience_orb.pickup" with volume 1 and pitch 1 to {_p}
    saveVariableData({_p}, false)